default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= Rails.application.credentials.dig(:TEMPLATE_APP_DATABASE_PASSWORD) %>
  database: <%= Rails.application.credentials.dig(:TEMPLATE_APP_DATABASE_NAME) %>
  port: 5432

development:
  <<: *default
  host: localhost

test:
  <<: *default

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:TEMPLATE_APP_HOST) %>